#!/usr/bin/env bash
# to get vk users's data
# use vk user ids as a target
# you can use several, separated with commas
targetid=$1;
fields=$2
api=https://api.vk.com/method;
curl -s "$api/users.get?user_ids=$targetid&fields=$fields"
